name: ActionsForGo

on:
  push:
    branches: [ master, features/* ]

  pull_request:
    branches: [ master, features/* ]

jobs:
  lint:
    name: go-lint-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32

  coverage:
    name: go-coverage-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test & coverage report
        run: |
          go test ./... -mod=readonly -race -coverprofile=coverage.txt -covermode=atomic -tags='ledger test_ledger_mock'
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  test:
    name: go-test-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/checkout@v2

    - name: vendor
      run: go mod vendor

    - name: test
      run: go test ./...