name: ActionsForGo

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master, features/* ]

jobs:
  go-lint-check:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32

  go-coverage-check:
    runs-on: self-hosted
    needs: go-test-check
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2
      - name: test & coverage report
        run: |
          go test -v -p 1 ./... -mod=readonly -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  go-test-check:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/checkout@v2

    - name: vendor
      run: go mod vendor

    - name: test
      run: go test -v -p 1 ./...